apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crasher-app
  namespace: argocd
spec:
  project: default
  source:
    # This is a test repo with intentionally failing pods
    repoURL: https://github.com/abhirockzz/kubernetes-chaos.git
    targetRevision: HEAD
    path: crash-loop-backoff
  destination:
    server: https://kubernetes.default.svc
    namespace: crasher-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
