apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crash-test-app
  namespace: argocd
spec:
  project: default
  source:
    # We'll deploy directly from local manifests using a ConfigMap approach
    # Or you can point this to YOUR GitHub repo
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: test-notifications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
