apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lsaid-crash-test
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.email: lsaid@softnet.co.tz
    notifications.argoproj.io/subscribe.on-sync-failed.email: lsaid@softnet.co.tz
    notifications.argoproj.io/subscribe.on-health-status-change.email: lsaid@softnet.co.tz
    notifications.argoproj.io/subscribe.on-pod-crash-loop.email: lsaid@softnet.co.tz
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: test-notifications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
